cloud:
  aws:
    s3:
      bucket: blush-market
    credentials:
      access-key: AKIAT7KMYIXV4MQ5KCPJ
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false